git:
  depth: 10
branches:
  only:
  - master
  - develop
language: objective-c
env:
- TERM=dumb
before_script:
- brew update >brew-update.log
- brew install ant >brew-install.log
- brew install caskroom/cask/brew-cask
- brew cask install flash-player-debugger
- export FLASHPLAYER_DEBUGGER="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash
  Player Debugger"
- export FLASH_PLAYER_EXE="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash
  Player Debugger"
- mkdir -p air_sdk
- wget -O AIRSDK_Compiler.tbz2 http://airdownload.adobe.com/air/mac/download/19.0/AIRSDK_Compiler.tbz2
- tar -xjf AIRSDK_Compiler.tbz2 -C air_sdk
- wget -O flex_sdk.zip http://mirrors.gigenet.com/apache/flex/4.14.1/binaries/apache-flex-sdk-4.14.1-bin.zip
- unzip -q flex_sdk.zip -d flex_sdk
- echo env.PLAYERGLOBAL_HOME=libs/player > flex_sdk/env.properties
- mkdir -p flex_sdk/frameworks/libs/player/11.1/
- mkdir -p flex_sdk/frameworks/libs/player/19.0/
- cp -f air_sdk/frameworks/libs/player/19.0/playerglobal.swc flex_sdk/frameworks/libs/player/11.1/
- cp -f air_sdk/frameworks/libs/player/19.0/playerglobal.swc flex_sdk/frameworks/libs/player/19.0/
- export FLEX_HOME="$TRAVIS_BUILD_DIR/flex_sdk"
- mkdir -p air_sdk/frameworks/libs/player/11.1/
- cp -f air_sdk/frameworks/libs/player/19.0/playerglobal.swc air_sdk/frameworks/libs/player/11.1/
- export AIR_HOME="$TRAVIS_BUILD_DIR/air_sdk"
- chmod +x flex_sdk/bin/mxmlc
script:
- ant -Dbuild.number=$TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: MVqBEzdBFMUZxFberVcyTVIHKQhRAzkggu7ryx3fsWF+20qnMo/elFCJdhw9MlsF2x4AqzUBnOVTcn7w3VOj9X6/EE8LEAMUmp2aUV9FK2cg/WpqkpbxkR7qadqRluRiiyLq48p1NaFXwwqFVj5pimHBXOC6dPEuc5QnrDvFC2LOs79Mi5ZMOchh53VPfFvTRe0HdAcJXyb8q64CZUN6UTDxuyVKZh5WglcP0vA+qpCCEeBAtbAHUTGpEFlB7AI570Ym9kuLBnEVqUistGPBvxs88SuoR+atdw16tNMGIJR1vPl85XdMbfLmjUbvlTWsDDpyCqmu2poX8+/zfwZlqAq2oCG7SrhdExMVuSW0T7I05yz278c74V4Z+0mgPUv5wbKErPP8J2Ps0y9mrvw4OIvodUCxRLnUDB+u92/tbNRwL5flXtxIhRqqiX7rZ1FtLbeza3/7wU+ypucVaoQq8thpWPmBsDz/1nrwukXG8ztBHRp0f8RbugaFqnk9airAgOj/ppVRqjCD+rlUcoEfBRmH/8qmjheEKZG3dCg8Z4ty63OsGdQ0X2Wn/MRofmS8ACcTcb59/lfEdNvCr/zmlhWJjLC+n+WpJTZNluMTgz4LCD5yX7t3otyHwiMO2iekUPviBGdhfIdFuXkI6ZlJvKDjiGRj9InLktFne+LZHSo=
  file: $TRAVIS_BUILD_DIR/lib/adobe-graphicscorelib-3.0.$TRAVIS_BUILD_NUMBER.swc
  on:
    repo: opprimendi/graphicscorelib
